/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ContactoRouteImport } from './routes/contacto'
import { Route as GaleriaRouteImport } from './routes/galeria'
import { Route as PrivacidadRouteImport } from './routes/privacidad'
import { Route as ServiciosRouteImport } from './routes/servicios'
import { Route as SobreNosotrosRouteImport } from './routes/sobre-nosotros'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminActualizarPasswordRouteImport } from './routes/admin/actualizar-password'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as TiendaIndexRouteImport } from './routes/tienda/index'
import { Route as TiendaSlugRouteImport } from './routes/tienda/$slug'
import { Route as AdminClientesIndexRouteImport } from './routes/admin/clientes/index'
import { Route as AdminClientesClienteIdRouteImport } from './routes/admin/clientes/$clienteId'
import { Route as AdminInventarioIndexRouteImport } from './routes/admin/inventario/index'
import { Route as AdminProductosIndexRouteImport } from './routes/admin/productos/index'
import { Route as AdminProductosProductoIdRouteImport } from './routes/admin/productos/$productoId'
import { Route as AdminProductosNuevoRouteImport } from './routes/admin/productos/nuevo'
import { Route as AdminReportesIndexRouteImport } from './routes/admin/reportes/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactoRoute = ContactoRouteImport.update({
  id: '/contacto',
  path: '/contacto',
  getParentRoute: () => rootRouteImport,
} as any)
const GaleriaRoute = GaleriaRouteImport.update({
  id: '/galeria',
  path: '/galeria',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadRoute = PrivacidadRouteImport.update({
  id: '/privacidad',
  path: '/privacidad',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiciosRoute = ServiciosRouteImport.update({
  id: '/servicios',
  path: '/servicios',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreNosotrosRoute = SobreNosotrosRouteImport.update({
  id: '/sobre-nosotros',
  path: '/sobre-nosotros',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminActualizarPasswordRoute = AdminActualizarPasswordRouteImport.update({
  id: '/admin/actualizar-password',
  path: '/admin/actualizar-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const TiendaIndexRoute = TiendaIndexRouteImport.update({
  id: '/tienda/',
  path: '/tienda/',
  getParentRoute: () => rootRouteImport,
} as any)
const TiendaSlugRoute = TiendaSlugRouteImport.update({
  id: '/tienda/$slug',
  path: '/tienda/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminClientesIndexRoute = AdminClientesIndexRouteImport.update({
  id: '/admin/clientes/',
  path: '/admin/clientes/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminClientesClienteIdRoute = AdminClientesClienteIdRouteImport.update({
  id: '/admin/clientes/$clienteId',
  path: '/admin/clientes/$clienteId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminInventarioIndexRoute = AdminInventarioIndexRouteImport.update({
  id: '/admin/inventario/',
  path: '/admin/inventario/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProductosIndexRoute = AdminProductosIndexRouteImport.update({
  id: '/admin/productos/',
  path: '/admin/productos/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProductosProductoIdRoute =
  AdminProductosProductoIdRouteImport.update({
    id: '/admin/productos/$productoId',
    path: '/admin/productos/$productoId',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminProductosNuevoRoute = AdminProductosNuevoRouteImport.update({
  id: '/admin/productos/nuevo',
  path: '/admin/productos/nuevo',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminReportesIndexRoute = AdminReportesIndexRouteImport.update({
  id: '/admin/reportes/',
  path: '/admin/reportes/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contacto': typeof ContactoRoute
  '/galeria': typeof GaleriaRoute
  '/privacidad': typeof PrivacidadRoute
  '/servicios': typeof ServiciosRoute
  '/sobre-nosotros': typeof SobreNosotrosRoute
  '/admin/actualizar-password': typeof AdminActualizarPasswordRoute
  '/admin/login': typeof AdminLoginRoute
  '/tienda/$slug': typeof TiendaSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/tienda/': typeof TiendaIndexRoute
  '/admin/clientes/$clienteId': typeof AdminClientesClienteIdRoute
  '/admin/productos/$productoId': typeof AdminProductosProductoIdRoute
  '/admin/productos/nuevo': typeof AdminProductosNuevoRoute
  '/admin/clientes/': typeof AdminClientesIndexRoute
  '/admin/inventario/': typeof AdminInventarioIndexRoute
  '/admin/productos/': typeof AdminProductosIndexRoute
  '/admin/reportes/': typeof AdminReportesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contacto': typeof ContactoRoute
  '/galeria': typeof GaleriaRoute
  '/privacidad': typeof PrivacidadRoute
  '/servicios': typeof ServiciosRoute
  '/sobre-nosotros': typeof SobreNosotrosRoute
  '/admin/actualizar-password': typeof AdminActualizarPasswordRoute
  '/admin/login': typeof AdminLoginRoute
  '/tienda/$slug': typeof TiendaSlugRoute
  '/admin': typeof AdminIndexRoute
  '/tienda': typeof TiendaIndexRoute
  '/admin/clientes/$clienteId': typeof AdminClientesClienteIdRoute
  '/admin/productos/$productoId': typeof AdminProductosProductoIdRoute
  '/admin/productos/nuevo': typeof AdminProductosNuevoRoute
  '/admin/clientes': typeof AdminClientesIndexRoute
  '/admin/inventario': typeof AdminInventarioIndexRoute
  '/admin/productos': typeof AdminProductosIndexRoute
  '/admin/reportes': typeof AdminReportesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contacto': typeof ContactoRoute
  '/galeria': typeof GaleriaRoute
  '/privacidad': typeof PrivacidadRoute
  '/servicios': typeof ServiciosRoute
  '/sobre-nosotros': typeof SobreNosotrosRoute
  '/admin/actualizar-password': typeof AdminActualizarPasswordRoute
  '/admin/login': typeof AdminLoginRoute
  '/tienda/$slug': typeof TiendaSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/tienda/': typeof TiendaIndexRoute
  '/admin/clientes/$clienteId': typeof AdminClientesClienteIdRoute
  '/admin/productos/$productoId': typeof AdminProductosProductoIdRoute
  '/admin/productos/nuevo': typeof AdminProductosNuevoRoute
  '/admin/clientes/': typeof AdminClientesIndexRoute
  '/admin/inventario/': typeof AdminInventarioIndexRoute
  '/admin/productos/': typeof AdminProductosIndexRoute
  '/admin/reportes/': typeof AdminReportesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contacto'
    | '/galeria'
    | '/privacidad'
    | '/servicios'
    | '/sobre-nosotros'
    | '/admin/actualizar-password'
    | '/admin/login'
    | '/tienda/$slug'
    | '/admin/'
    | '/tienda/'
    | '/admin/clientes/$clienteId'
    | '/admin/productos/$productoId'
    | '/admin/productos/nuevo'
    | '/admin/clientes/'
    | '/admin/inventario/'
    | '/admin/productos/'
    | '/admin/reportes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contacto'
    | '/galeria'
    | '/privacidad'
    | '/servicios'
    | '/sobre-nosotros'
    | '/admin/actualizar-password'
    | '/admin/login'
    | '/tienda/$slug'
    | '/admin'
    | '/tienda'
    | '/admin/clientes/$clienteId'
    | '/admin/productos/$productoId'
    | '/admin/productos/nuevo'
    | '/admin/clientes'
    | '/admin/inventario'
    | '/admin/productos'
    | '/admin/reportes'
  id:
    | '__root__'
    | '/'
    | '/contacto'
    | '/galeria'
    | '/privacidad'
    | '/servicios'
    | '/sobre-nosotros'
    | '/admin/actualizar-password'
    | '/admin/login'
    | '/tienda/$slug'
    | '/admin/'
    | '/tienda/'
    | '/admin/clientes/$clienteId'
    | '/admin/productos/$productoId'
    | '/admin/productos/nuevo'
    | '/admin/clientes/'
    | '/admin/inventario/'
    | '/admin/productos/'
    | '/admin/reportes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactoRoute: typeof ContactoRoute
  GaleriaRoute: typeof GaleriaRoute
  PrivacidadRoute: typeof PrivacidadRoute
  ServiciosRoute: typeof ServiciosRoute
  SobreNosotrosRoute: typeof SobreNosotrosRoute
  AdminActualizarPasswordRoute: typeof AdminActualizarPasswordRoute
  AdminLoginRoute: typeof AdminLoginRoute
  TiendaSlugRoute: typeof TiendaSlugRoute
  AdminIndexRoute: typeof AdminIndexRoute
  TiendaIndexRoute: typeof TiendaIndexRoute
  AdminClientesClienteIdRoute: typeof AdminClientesClienteIdRoute
  AdminProductosProductoIdRoute: typeof AdminProductosProductoIdRoute
  AdminProductosNuevoRoute: typeof AdminProductosNuevoRoute
  AdminClientesIndexRoute: typeof AdminClientesIndexRoute
  AdminInventarioIndexRoute: typeof AdminInventarioIndexRoute
  AdminProductosIndexRoute: typeof AdminProductosIndexRoute
  AdminReportesIndexRoute: typeof AdminReportesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacto': {
      id: '/contacto'
      path: '/contacto'
      fullPath: '/contacto'
      preLoaderRoute: typeof ContactoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/galeria': {
      id: '/galeria'
      path: '/galeria'
      fullPath: '/galeria'
      preLoaderRoute: typeof GaleriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidad': {
      id: '/privacidad'
      path: '/privacidad'
      fullPath: '/privacidad'
      preLoaderRoute: typeof PrivacidadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicios': {
      id: '/servicios'
      path: '/servicios'
      fullPath: '/servicios'
      preLoaderRoute: typeof ServiciosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre-nosotros': {
      id: '/sobre-nosotros'
      path: '/sobre-nosotros'
      fullPath: '/sobre-nosotros'
      preLoaderRoute: typeof SobreNosotrosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/actualizar-password': {
      id: '/admin/actualizar-password'
      path: '/admin/actualizar-password'
      fullPath: '/admin/actualizar-password'
      preLoaderRoute: typeof AdminActualizarPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tienda/': {
      id: '/tienda/'
      path: '/tienda'
      fullPath: '/tienda/'
      preLoaderRoute: typeof TiendaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tienda/$slug': {
      id: '/tienda/$slug'
      path: '/tienda/$slug'
      fullPath: '/tienda/$slug'
      preLoaderRoute: typeof TiendaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/clientes/': {
      id: '/admin/clientes/'
      path: '/admin/clientes'
      fullPath: '/admin/clientes/'
      preLoaderRoute: typeof AdminClientesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/clientes/$clienteId': {
      id: '/admin/clientes/$clienteId'
      path: '/admin/clientes/$clienteId'
      fullPath: '/admin/clientes/$clienteId'
      preLoaderRoute: typeof AdminClientesClienteIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/inventario/': {
      id: '/admin/inventario/'
      path: '/admin/inventario'
      fullPath: '/admin/inventario/'
      preLoaderRoute: typeof AdminInventarioIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/productos/': {
      id: '/admin/productos/'
      path: '/admin/productos'
      fullPath: '/admin/productos/'
      preLoaderRoute: typeof AdminProductosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/productos/$productoId': {
      id: '/admin/productos/$productoId'
      path: '/admin/productos/$productoId'
      fullPath: '/admin/productos/$productoId'
      preLoaderRoute: typeof AdminProductosProductoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/productos/nuevo': {
      id: '/admin/productos/nuevo'
      path: '/admin/productos/nuevo'
      fullPath: '/admin/productos/nuevo'
      preLoaderRoute: typeof AdminProductosNuevoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/reportes/': {
      id: '/admin/reportes/'
      path: '/admin/reportes'
      fullPath: '/admin/reportes/'
      preLoaderRoute: typeof AdminReportesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactoRoute: ContactoRoute,
  GaleriaRoute: GaleriaRoute,
  PrivacidadRoute: PrivacidadRoute,
  ServiciosRoute: ServiciosRoute,
  SobreNosotrosRoute: SobreNosotrosRoute,
  AdminActualizarPasswordRoute: AdminActualizarPasswordRoute,
  AdminLoginRoute: AdminLoginRoute,
  TiendaSlugRoute: TiendaSlugRoute,
  AdminIndexRoute: AdminIndexRoute,
  TiendaIndexRoute: TiendaIndexRoute,
  AdminClientesClienteIdRoute: AdminClientesClienteIdRoute,
  AdminProductosProductoIdRoute: AdminProductosProductoIdRoute,
  AdminProductosNuevoRoute: AdminProductosNuevoRoute,
  AdminClientesIndexRoute: AdminClientesIndexRoute,
  AdminInventarioIndexRoute: AdminInventarioIndexRoute,
  AdminProductosIndexRoute: AdminProductosIndexRoute,
  AdminReportesIndexRoute: AdminReportesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
