/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ContactoRouteImport } from './routes/contacto'
import { Route as GaleriaRouteImport } from './routes/galeria'
import { Route as ServiciosRouteImport } from './routes/servicios'
import { Route as SobreNosotrosRouteImport } from './routes/sobre-nosotros'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as TiendaIndexRouteImport } from './routes/tienda/index'
import { Route as TiendaSlugRouteImport } from './routes/tienda/$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactoRoute = ContactoRouteImport.update({
  id: '/contacto',
  path: '/contacto',
  getParentRoute: () => rootRouteImport,
} as any)
const GaleriaRoute = GaleriaRouteImport.update({
  id: '/galeria',
  path: '/galeria',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiciosRoute = ServiciosRouteImport.update({
  id: '/servicios',
  path: '/servicios',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreNosotrosRoute = SobreNosotrosRouteImport.update({
  id: '/sobre-nosotros',
  path: '/sobre-nosotros',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const TiendaIndexRoute = TiendaIndexRouteImport.update({
  id: '/tienda/',
  path: '/tienda/',
  getParentRoute: () => rootRouteImport,
} as any)
const TiendaSlugRoute = TiendaSlugRouteImport.update({
  id: '/tienda/$slug',
  path: '/tienda/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contacto': typeof ContactoRoute
  '/galeria': typeof GaleriaRoute
  '/servicios': typeof ServiciosRoute
  '/sobre-nosotros': typeof SobreNosotrosRoute
  '/admin/login': typeof AdminLoginRoute
  '/tienda/$slug': typeof TiendaSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/tienda/': typeof TiendaIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contacto': typeof ContactoRoute
  '/galeria': typeof GaleriaRoute
  '/servicios': typeof ServiciosRoute
  '/sobre-nosotros': typeof SobreNosotrosRoute
  '/admin/login': typeof AdminLoginRoute
  '/tienda/$slug': typeof TiendaSlugRoute
  '/admin': typeof AdminIndexRoute
  '/tienda': typeof TiendaIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contacto': typeof ContactoRoute
  '/galeria': typeof GaleriaRoute
  '/servicios': typeof ServiciosRoute
  '/sobre-nosotros': typeof SobreNosotrosRoute
  '/admin/login': typeof AdminLoginRoute
  '/tienda/$slug': typeof TiendaSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/tienda/': typeof TiendaIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contacto'
    | '/galeria'
    | '/servicios'
    | '/sobre-nosotros'
    | '/admin/login'
    | '/tienda/$slug'
    | '/admin/'
    | '/tienda/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contacto'
    | '/galeria'
    | '/servicios'
    | '/sobre-nosotros'
    | '/admin/login'
    | '/tienda/$slug'
    | '/admin'
    | '/tienda'
  id:
    | '__root__'
    | '/'
    | '/contacto'
    | '/galeria'
    | '/servicios'
    | '/sobre-nosotros'
    | '/admin/login'
    | '/tienda/$slug'
    | '/admin/'
    | '/tienda/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactoRoute: typeof ContactoRoute
  GaleriaRoute: typeof GaleriaRoute
  ServiciosRoute: typeof ServiciosRoute
  SobreNosotrosRoute: typeof SobreNosotrosRoute
  AdminLoginRoute: typeof AdminLoginRoute
  TiendaSlugRoute: typeof TiendaSlugRoute
  AdminIndexRoute: typeof AdminIndexRoute
  TiendaIndexRoute: typeof TiendaIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacto': {
      id: '/contacto'
      path: '/contacto'
      fullPath: '/contacto'
      preLoaderRoute: typeof ContactoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/galeria': {
      id: '/galeria'
      path: '/galeria'
      fullPath: '/galeria'
      preLoaderRoute: typeof GaleriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicios': {
      id: '/servicios'
      path: '/servicios'
      fullPath: '/servicios'
      preLoaderRoute: typeof ServiciosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre-nosotros': {
      id: '/sobre-nosotros'
      path: '/sobre-nosotros'
      fullPath: '/sobre-nosotros'
      preLoaderRoute: typeof SobreNosotrosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tienda/': {
      id: '/tienda/'
      path: '/tienda'
      fullPath: '/tienda/'
      preLoaderRoute: typeof TiendaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tienda/$slug': {
      id: '/tienda/$slug'
      path: '/tienda/$slug'
      fullPath: '/tienda/$slug'
      preLoaderRoute: typeof TiendaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactoRoute: ContactoRoute,
  GaleriaRoute: GaleriaRoute,
  ServiciosRoute: ServiciosRoute,
  SobreNosotrosRoute: SobreNosotrosRoute,
  AdminLoginRoute: AdminLoginRoute,
  TiendaSlugRoute: TiendaSlugRoute,
  AdminIndexRoute: AdminIndexRoute,
  TiendaIndexRoute: TiendaIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
